version: "3"

services:
  client:
    build: ./front
    container_name: clientchallenge
    ports:
      - "80:80"
    volumes:
      - .:/client
    networks:
      - bridgechallenge
    entrypoint: "npm start"
    links:
      - api
    depends_on:
      - api

    restart: on-failure

  api:
    build: ./api
    container_name: apichallenge
    ports:
      - "5000:5000"
    volumes:
      - .:/api
    networks:
      - bridgechallenge
    entrypoint: "npm start"

    restart: on-failure

networks:
  bridgechallenge:
    driver: bridge
