version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - bridge

  client:
    build: ./front
    container_name: clientchallenge
    ports:
      - "80:80"
    volumes:
      - .:/client
    networks:
      - bridge
    entrypoint: "npm start"

    depends_on:
      elasticsearch:
        condition: service_healthy

    restart: on-failure

  api:
    build: ./api
    container_name: apichallenge
    ports:
      - "5000:5000"
    volumes:
      - .:/api
    networks:
      - bridge
    entrypoint: "npm start"
    depends_on:
      
    restart: on-failure
    links:
      - elasticsearch

networks:
  bridge:
